
    <?php
    // $categoryProducts = $block->getProductCollectionByCategories();

    // if ($categoryProducts != null) {
    //     foreach ($categoryProducts as $product) {
    //         echo 'Nombre: ' . $product->getName() . ' - ID: ' . $product->getId() . ' - URL imagen: ' . $product->getImage() . '<br />';
    //     }
    // } else {
    //     echo 'era null';
    // }

    /**
     * @var \NTTData\Practice\Block\Product\List\Products $block
     */

    echo '<h3>' . get_class($block) . '</h3>';
    ?>
